baseurl = "/"
languageCode = "en-us"
title = "web"
theme = "hugo-protagonist"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    AuthorName = "Mike Rombout"
    description = "A simple, minimal blog for those who love text."

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 3

[markup]
    [markup.highlight]
        style = "emacs"
    [markup.goldmark.renderer]
        unsafe = true

[privacy]
    [privacy.youtube]
        disable = false
        privacyEnhanced = true